name: Test Suite

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        # Support only LTS and Current build of node
        # See https://github.com/nodejs/Release
        node-version: [ 16.x, 18.x, 20.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm install
      - run: npm run lint:test

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [ 'eslint' ]
    strategy:
      matrix:
        node-version: [ 16.x, 18.x, 20.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm install
      - run: npm run test

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [ 'test' ]
    strategy:
      matrix:
        node-version: [ 16.x, 18.x, 20.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm install
      - run: npm run build
